name:                TP1
version:             0.1.0.0
github:              "piface314/TP1"
license:             BSD3
author:              "Henrique Santana"
maintainer:          "henrique.s.santana@ufv.br"
copyright:           "2021 Henrique Santana"

extra-source-files:
- README.md

description:         Please see the README on GitHub at <https://github.com/piface314/TP1#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  TP1-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP1

tests:
  TP1-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - TP1
